repos:
-   repo: https://gitlab.com/vojko.pribudic.foss/pre-commit-update
    rev: v0.8.0
    hooks:
    -   id: pre-commit-update
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-json
    -   id: detect-private-key
    -   id: requirements-txt-fixer
-   repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
    -   id: codespell
        exclude: ^locale/
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.0
    hooks:
    -   id: ruff-check
        args: [--fix]
    -   id: ruff-format
