name: Build builder-base image
on:
  workflow_call

jobs:
  build-base:
    runs-on: ubuntu-20.04
    name: Build builder-base image
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Get docker image hashes
        run: bash tools/pre-fetch-images.sh
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ hashFiles('deploy/Dockerfile', 'img_hashes', 'requirements*', 'tox.ini') }}
      - name: Build builder-base image
        uses: docker/build-push-action@v3
        with:
          push: false
          file: deploy/Dockerfile
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          context: ./
          tags: builder-base:latest
          target: builder-base
